In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [19]:
df = pd.read_csv("glass.csv")

In [20]:
df.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [21]:
X = df.drop('Type',axis=1)
y = df['Type']

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [23]:
distances = [['Euclidean','euclidean'],['Manhattan','manhattan']]

In [24]:
for name, metric in distances:
  model = KNeighborsClassifier(n_neighbors=3,metric=metric)
  model.fit(X_train,y_train)
  y_pred=model.predict(X_test)
  print(f"\n___With {name} Metric___")
  print(f"Accuracy Score: {accuracy_score(y_pred,y_test)}")
  print("Confusion Matrix: ")
  cm = confusion_matrix(y_test,y_pred)
  print(cm)


___With Euclidean Metric___
Accuracy Score: 0.6307692307692307
Confusion Matrix: 
[[17  5  3  0  0  0]
 [ 5  9  0  2  1  0]
 [ 2  1  1  0  0  0]
 [ 0  0  0  3  0  2]
 [ 0  1  0  0  2  1]
 [ 1  0  0  0  0  9]]

___With Manhattan Metric___
Accuracy Score: 0.676923076923077
Confusion Matrix: 
[[18  4  3  0  0  0]
 [ 5 10  0  1  1  0]
 [ 3  0  1  0  0  0]
 [ 0  2  0  3  0  0]
 [ 0  1  0  0  3  0]
 [ 1  0  0  0  0  9]]
